name: default

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: install boost and related packages
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    # build project
    - name: create the build folder
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
      env:
        MAKEFLAGS: "-j2"
    # run tests
    - name: run the test
      run: build/boost-helloworld
    # upload artifact with our binary
    - name: Upload the binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary
        path: build/boost-helloworld
